<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_lp-plus-wide',
		'title' => 'LP PLUS wide',
		'fields' => array (
			array (
				'key' => 'field_548beda952329',
				'label' => '■サイト幅の設定',
				'name' => 'm_widthw',
				'type' => 'text',
				'instructions' => 'ランディンページの幅を設定して下さい。デフォルトは900pxです。',
				'default_value' => '900px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548beebb5232a',
				'label' => '■コンテンツ幅の設定',
				'name' => 'c_widthw',
				'type' => 'text',
				'instructions' => 'コンテンツの表示幅を設定して下さい。デフォルトは800pxです。',
				'default_value' => '800px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548d14112e22b',
				'label' => '■コンテンツ両サイドマージン',
				'name' => 'p_tag_sidew',
				'type' => 'text',
				'instructions' => 'サイト幅とコンテンツ幅を同じにした場合などにご使用ください。&lt;div class="side_m"&gt;～&lt;/div&gt;内の文章の両サイドにマージンを設定することができます。',
				'default_value' => '0px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548beee65232b',
				'label' => '■タイトルバーカラーの設定',
				'name' => 'tbarw',
				'type' => 'color_picker',
				'instructions' => 'タイトルバーのボーダーカラーを設定して下さい。',
				'default_value' => '#1e73be',
			),
			array (
				'key' => 'field_548bef355232c',
				'label' => '■ヘッダー画像の設定（ワイド画像）',
				'name' => 'main_headerw',
				'type' => 'image',
				'instructions' => 'ヘッダー画像をアップロードして下さい。',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_548bed7152328',
				'label' => '■サイト枠装飾',
				'name' => 'side_dsw',
				'type' => 'radio',
				'choices' => array (
					'onelpw' => 'シャドウ',
					'onelpLw' => 'ライン',
					'onelpNw' => 'なし',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_548bef765232d',
				'label' => '●サイト内背景',
				'name' => 'bg_cw',
				'type' => 'color_picker',
				'instructions' => 'サイト内の背景に色を付けたい場合は、色の設定をしてください。デフォルトは白色です。',
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_548befc45232e',
				'label' => '●サイト内背景 画像',
				'name' => 'bg_iw',
				'type' => 'image',
				'instructions' => 'サイト内の背景に画像を設定したい場合は、画像をアップロードしてください。縦にリピートします。',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_548beff75232f',
				'label' => '◆背景',
				'name' => 'bgcw',
				'type' => 'color_picker',
				'instructions' => 'ページの背景に色を付けたい場合は、色の設定をしてください。デフォルトは白色です。',
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_548bf03952330',
				'label' => '◆背景 画像',
				'name' => 'bgiw',
				'type' => 'image',
				'instructions' => 'ページの背景に画像を設定したい場合は、画像をアップロードしてください。（リピートのみ）',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}