<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_lp-plus-normal',
		'title' => 'LP PLUS normal',
		'fields' => array (
			array (
				'key' => 'field_548661162817b',
				'label' => '■サイト幅の設定',
				'name' => 'm_width',
				'type' => 'text',
				'instructions' => 'ランディンページの幅を設定して下さい。デフォルトは900pxです。',
				'default_value' => '900px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548661212817c',
				'label' => '■コンテンツ幅の設定',
				'name' => 'c_width',
				'type' => 'text',
				'instructions' => 'コンテンツの表示幅を設定して下さい。デフォルトは800pxです。',
				'default_value' => '800px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548d1716c2038',
				'label' => '■コンテンツ 両サイドマージン',
				'name' => 'p_tag_side',
				'type' => 'text',
				'instructions' => 'サイト幅とコンテンツ幅を同じにした場合などにご使用ください。&lt;div class="side_m"&gt;～&lt;/div&gt;内の文章の両サイドにマージンを設定することができます。',
				'default_value' => '0px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548661302817d',
				'label' => '■タイトルバーカラーの設定',
				'name' => 'tbar',
				'type' => 'color_picker',
				'instructions' => 'タイトルバーのボーダーカラーを設定して下さい。',
				'default_value' => '#1e73be',
			),
			array (
				'key' => 'field_548661392817e',
				'label' => '■ヘッダー画像の設定（標準画像）',
				'name' => 'main_header',
				'type' => 'image',
				'instructions' => 'ヘッダー画像をアップロードして下さい。',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_548661432817f',
				'label' => '■サイト枠装飾',
				'name' => 'side_ds',
				'type' => 'radio',
				'choices' => array (
					'onelp' => 'シャドウ',
					'onelpL' => 'ライン',
					'onelpN' => 'なし',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'onelp',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5486614e28180',
				'label' => '●サイト内背景',
				'name' => 'bg_c',
				'type' => 'color_picker',
				'instructions' => 'サイト内の背景に色を付けたい場合は、色の設定をしてください。デフォルトは白色です。',
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_5486615728181',
				'label' => '●サイト内背景 画像',
				'name' => 'bg_i',
				'type' => 'image',
				'instructions' => 'サイト内の背景に画像を設定したい場合は、画像をアップロードしてください。縦にリピートします。',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5486616428182',
				'label' => '◆背景',
				'name' => 'bgc',
				'type' => 'color_picker',
				'instructions' => 'ページの背景に色を付けたい場合は、色の設定をしてください。デフォルトは白色です。',
				'default_value' => '#ffffff',
			),
			array (
				'key' => 'field_5486616e28183',
				'label' => '◆背景 画像',
				'name' => 'bgi',
				'type' => 'image',
				'instructions' => 'ページの背景に画像を設定したい場合は、画像をアップロードしてください。（リピートのみ）',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
}